---
efiSystemPartition: "/boot/efi"

userSwapChoices:
  - none
  - small
  - suspend
  - file

defaultPartitionTableType: gpt
defaultFilesystemType: "btrfs"
createHybridBootloaderLayout: true

allowManualPartitioning: true
