import colorsys
import os

from services.settings import SettingsService


class AccentService:

    COLORS = {

        "Blue": "#3584E4",

        "Purple": "#9141AC",

        "Pink": "#E01B9C",

        "Red": "#E62D2D",

        "Orange": "#E66100",

        "Yellow": "#F5C211",

        "Green": "#2EC27E",

        "Teal": "#1C71D8"

    }

    ACCENT_CSS = os.path.join(
        os.path.expanduser("~"),
        ".config",
        "churros",
        "accent.css"
    )

    @classmethod
    def current(cls):

        return SettingsService.get("accent.color", "Blue")

    @classmethod
    def available(cls):

        return list(cls.COLORS.keys())

    @classmethod
    def hex_for(cls, name):

        return cls.COLORS.get(name, cls.COLORS["Orange"])

    @classmethod
    def _hex_to_rgb(cls, hex_color):

        hex_color = hex_color.lstrip("#")

        return tuple(
            int(hex_color[i:i + 2], 16) / 255.0
            for i in (0, 2, 4)
        )

    @classmethod
    def _rgb_to_hex(cls, rgb):

        return "#{:02x}{:02x}{:02x}".format(*[
            max(0, min(255, int(c * 255)))
            for c in rgb
        ])

    @classmethod
    def _adjust(cls, hex_color, light_delta=0.0, sat_delta=0.0):

        r, g, b = cls._hex_to_rgb(hex_color)

        h, l, s = colorsys.rgb_to_hls(r, g, b)

        l = max(0.0, min(1.0, l + light_delta))

        s = max(0.0, min(1.0, s + sat_delta))

        r2, g2, b2 = colorsys.hls_to_rgb(h, l, s)

        return cls._rgb_to_hex((r2, g2, b2))

    @classmethod
    def _generate_accent_css(cls, color_name):

        base = cls.hex_for(color_name)

        return cls._build_accent_css(base, source="churros set-accent")

    @classmethod
    def _generate_accent_css_hex(cls, base_hex):

        base = base_hex if base_hex.startswith("#") else "#" + base_hex

        return cls._build_accent_css(base, source="dynamic colors (pywal)")

    @classmethod
    def _build_accent_css(cls, base, source):

        strong = cls._adjust(base, light_delta=-0.08)

        soft = cls._adjust(base, light_delta=0.18)

        return (
            "/* Auto-generated by " + source + ". Do not edit. */\n"
            "window {\n"
            "    --accent: " + base + ";\n"
            "    --accent-strong: " + strong + ";\n"
            "    --accent-soft: " + soft + ";\n"
            "    --accent-text: #ffffff;\n"
            "    --accent-bg-hover: " + cls._adjust(base, light_delta=0.32) + ";\n"
            "    --accent-glow: 0 0 20px " + cls._adjust(base, light_delta=0.0, sat_delta=0.0) + "40;\n"
            "}\n"
        )

    @classmethod
    def _write_accent_css(cls, color_name):

        directory = os.path.dirname(cls.ACCENT_CSS)

        os.makedirs(directory, exist_ok=True)

        with open(cls.ACCENT_CSS, "w") as file:

            file.write(cls._generate_accent_css(color_name))

    @classmethod
    def _write_accent_css_hex(cls, base_hex):

        directory = os.path.dirname(cls.ACCENT_CSS)

        os.makedirs(directory, exist_ok=True)

        with open(cls.ACCENT_CSS, "w") as file:

            file.write(cls._generate_accent_css_hex(base_hex))

    @classmethod
    def set(cls, color):

        SettingsService.set("accent.color", color)

        cls._write_accent_css(color)

        try:

            from services.pywal_service import PywalService

            if PywalService.enabled():

                palette = PywalService.generate()

                if palette is not None:

                    PywalService.apply_accent(palette)

        except Exception:

            pass

    @classmethod
    def set_hex(cls, hex_color):

        """Escribe accent.css con un color hex arbitrario (para pywal).

        NO persiste en settings.json: el color custom se sobreescribe
        la proxima vez que el usuario elige un color con nombre.
        """

        cls._write_accent_css_hex(hex_color)

    @classmethod
    def ensure(cls):

        color = cls.current()

        if not os.path.exists(cls.ACCENT_CSS):

            cls._write_accent_css(color)
