import json
import os
import shutil
import subprocess
import time


HOME = os.path.expanduser("~")
CONFIG_PATH = os.path.join(HOME, ".config", "waybar", "config.jsonc")
STYLE_PATH = os.path.join(HOME, ".config", "waybar", "style.css")
COLORS_PATH = os.path.join(HOME, ".config", "waybar", "colors-waybar.css")


DEFAULTS = {
    "layer": "top",
    "position": "top",
    "spacing": 0,
    "height": 30,
    "font-size": 14,
    "font-family": "JetBrainsMono Nerd Font",
    "background": "#2a1612",
    "foreground": "#c9c4c3",
    "accent": "#DE8636",
    "background-alpha": 0.9,
}


def _read_jsonc(path):
    if not os.path.exists(path):
        return {}
    try:
        with open(path) as f:
            raw = f.read()
        cleaned = []
        in_string = False
        in_comment = False
        escape = False
        for ch in raw:
            if in_comment:
                if ch == "\n":
                    in_comment = False
                    cleaned.append("\n")
                continue
            if in_string:
                cleaned.append(ch)
                if escape:
                    escape = False
                    continue
                if ch == "\\":
                    escape = True
                    continue
                if ch == '"':
                    in_string = False
                continue
            if ch == "/" and cleaned and cleaned[-1] == "/":
                cleaned.pop()
                in_comment = True
                continue
            if ch == '"':
                in_string = True
            cleaned.append(ch)
        return json.loads("".join(cleaned))
    except Exception:
        return {}


def _write_jsonc(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    text = json.dumps(data, indent=2)
    with open(path, "w") as f:
        f.write("// Auto-generated by churros-settings WaybarService\n")
        f.write("// Editalo desde Preferencias -> Waybar\n")
        f.write(text)


def _build_env():
    env = os.environ.copy()
    if not env.get("WAYLAND_DISPLAY"):
        xrd = env.get("XDG_RUNTIME_DIR", f"/run/user/{os.getuid()}")
        if os.path.isdir(xrd):
            for sock in sorted(os.listdir(xrd)):
                if sock.startswith("wayland-"):
                    env["WAYLAND_DISPLAY"] = sock
                    break
    if not env.get("XDG_RUNTIME_DIR"):
        env["XDG_RUNTIME_DIR"] = f"/run/user/{os.getuid()}"
    return env


class WaybarService:

    @classmethod
    def config_path(cls):
        return CONFIG_PATH

    @classmethod
    def style_path(cls):
        return STYLE_PATH

    @classmethod
    def colors_path(cls):
        return COLORS_PATH

    @classmethod
    def defaults(cls):
        return dict(DEFAULTS)

    @classmethod
    def get(cls):

        cfg = _read_jsonc(CONFIG_PATH)
        colors = cls._read_colors()

        return {
            "layer":            cfg.get("layer", DEFAULTS["layer"]),
            "position":         cfg.get("position", DEFAULTS["position"]),
            "spacing":          cfg.get("spacing", DEFAULTS["spacing"]),
            "height":           cfg.get("height", DEFAULTS["height"]),
            "font-size":        colors.get("font-size", DEFAULTS["font-size"]),
            "font-family":      colors.get("font-family", DEFAULTS["font-family"]),
            "background":       colors.get("background", DEFAULTS["background"]),
            "foreground":       colors.get("foreground", DEFAULTS["foreground"]),
            "accent":           colors.get("accent", DEFAULTS["accent"]),
            "background-alpha": colors.get("background-alpha", DEFAULTS["background-alpha"]),
            "modules-left":     cfg.get("modules-left", []),
            "modules-center":   cfg.get("modules-center", []),
            "modules-right":    cfg.get("modules-right", []),
        }

    @classmethod
    def set(cls, values, reload_kind="auto"):

        cfg = _read_jsonc(CONFIG_PATH)

        cfg["layer"] = values.get("layer", DEFAULTS["layer"])
        cfg["position"] = values.get("position", DEFAULTS["position"])
        cfg["spacing"] = int(values.get("spacing", DEFAULTS["spacing"]))
        cfg["height"] = int(values.get("height", DEFAULTS["height"]))

        for key in ("modules-left", "modules-center", "modules-right"):
            modules = values.get(key)
            if modules is not None:
                cfg[key] = modules

        _write_jsonc(CONFIG_PATH, cfg)
        cls._write_colors(values)
        cls._write_style(values)
        cls.reload(full_restart=True)

    @classmethod
    def _read_colors(cls):
        result = {}
        if not os.path.exists(COLORS_PATH):
            return result
        try:
            with open(COLORS_PATH) as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("@import") or line.startswith("/*"):
                        continue
                    if line.startswith("@define-color"):
                        parts = line.split(maxsplit=2)
                        if len(parts) >= 3:
                            name = parts[1].lstrip("@")
                            value = parts[2].rstrip(";")
                            result[name] = value
        except Exception:
            pass
        return result

    @classmethod
    def _write_colors(cls, values):
        os.makedirs(os.path.dirname(COLORS_PATH), exist_ok=True)
        bg = values.get("background", DEFAULTS["background"])
        fg = values.get("foreground", DEFAULTS["foreground"])
        accent = values.get("accent", DEFAULTS["accent"])
        content = (
            f"@define-color background {bg};\n"
            f"@define-color foreground {fg};\n"
            f"@define-color color4 {accent};\n"
            f"@define-color color1 {accent};\n"
        )
        with open(COLORS_PATH, "w") as f:
            f.write(content)
        cls._write_style(values)

    @classmethod
    def _write_style(cls, values):
        os.makedirs(os.path.dirname(STYLE_PATH), exist_ok=True)
        font_size = int(values.get("font-size", DEFAULTS["font-size"]))
        font_family = values.get("font-family", DEFAULTS["font-family"])
        bg_alpha = float(values.get("background-alpha", DEFAULTS["background-alpha"]))

        css = f"""/* ChurrOS Waybar — Liquid Glass   (auto-generated) */

@import "./colors-waybar.css";

* {{
    background-color: alpha(@background, {bg_alpha:.2f});
    color: @foreground;
    border: none;
    border-radius: 0;
    min-height: 0;
    font-family: '{font_family}';
    font-size: {font_size}px;
    border: 0px solid alpha(@foreground, 0.6);
}}

window#waybar {{
    background-color: transparent;
    color: @foreground;
}}

.modules-left {{
    margin-left: 5px;
}}

.modules-right {{
    margin-right: 5px;
}}

#workspaces {{
    padding: 0 4px;
    margin: 4px 4px;
    border-radius: 12px;
    background-color: alpha(@background, {max(0.0, bg_alpha - 0.2):.2f});
    border: 1px solid alpha(@foreground, 0.06);
}}

#workspaces button {{
    all: initial;
    padding: 0 6px;
    margin: 2px 1px;
    min-width: 9px;
    border-radius: 6px;
    color: alpha(@foreground, 0.5);
}}

#workspaces button.empty {{
    opacity: 0.45;
}}

#workspaces button.active,
#workspaces button.focused {{
    background-color: alpha(@color4, 0.30);
    color: @foreground;
}}

#workspaces button:hover {{
    background-color: alpha(@color4, 0.12);
}}

#cpu,
#idle_inhibitor,
#battery,
#custom-screenrecording-indicator,
#custom-dnd {{
    min-width: 10px;
    margin: 0 7.5px;
}}

#custom-launcher {{
    margin-left: 2px;
    margin-right: 8px;
    background-color: alpha(@color4, 0.20);
    padding: 4px 10px;
    border-radius: 10px;
    color: @color4;
}}

#custom-launcher:hover {{
    background-color: alpha(@color4, 0.35);
}}

#pulseaudio {{
    margin-right: 4px;
    margin-left: 1px;
}}

#tray {{
    margin-right: 4px;
}}

#bluetooth {{
    margin-right: 2px;
}}

#network {{
    margin-right: 10px;
    margin-left: 6px;
}}

#custom-expand-icon {{
    margin-right: 10px;
}}

tooltip {{
    padding: 4px 8px;
    border-radius: 8px;
    background-color: alpha(@background, 0.90);
    border: 1px solid alpha(@foreground, 0.08);
}}

#clock {{
    margin-left: 8px;
    font-weight: 600;
}}

.hidden {{
    opacity: 0;
}}

#custom-screenrecording-indicator {{
    min-width: 12px;
    margin-left: 8px;
    font-size: 10px;
}}

#custom-screenrecording-indicator.active {{
    color: #a55555;
}}

#custom-dnd.active {{
    color: @color4;
}}

#mpris {{
    font-weight: 600;
    border-radius: 14px;
    padding: 2px 8px;
    margin: 2px 2px;
    background-color: alpha(@background, {max(0.0, bg_alpha - 0.2):.2f});
}}

#memory,
#disk,
#cpu,
#battery,
#backlight,
#network,
#bluetooth,
#pulseaudio,
#idle_inhibitor,
#custom-dnd {{
    padding: 0 4px;
    border-radius: 8px;
}}

#memory:hover,
#disk:hover,
#cpu:hover,
#battery:hover,
#backlight:hover,
#network:hover,
#bluetooth:hover,
#pulseaudio:hover,
#idle_inhibitor:hover,
#custom-dnd:hover {{
    background-color: alpha(@color4, 0.12);
}}

#battery.warning {{
    color: #f59e0b;
}}

#battery.critical {{
    color: #ef4444;
}}

#battery.charging {{
    color: @color4;
}}

#custom/sep {{
    color: alpha(@foreground, 0.20);
    margin: 0 4px;
}}
"""

        with open(STYLE_PATH, "w") as f:
            f.write(css)

    @classmethod
    def reload(cls, full_restart=True):

        env = _build_env()

        log_path = "/tmp/waybar.log"

        try:

            subprocess.run(
                ["pkill", "-x", "waybar"],
                capture_output=True, timeout=2, env=env,
            )
        except Exception:
            pass

        time.sleep(1.0)

        try:
            pg = subprocess.run(
                ["pgrep", "-x", "waybar"],
                capture_output=True, timeout=1, env=env,
            )
            if pg.returncode == 0:
                time.sleep(0.8)
                subprocess.run(
                    ["pkill", "-9", "-x", "waybar"],
                    capture_output=True, timeout=2, env=env,
                )
                time.sleep(0.5)
        except Exception:
            pass

        if shutil.which("waybar") is None:
            print("[waybar] waybar no instalado, no recargo")
            return

        try:

            with open(log_path, "a") as logf:
                logf.write(
                    "\n=== waybar reload {} ===\n".format(
                        time.strftime("%H:%M:%S")
                    )
                )
                logf.flush()

                subprocess.Popen(
                    ["waybar"],
                    stdout=logf,
                    stderr=subprocess.STDOUT,
                    start_new_session=True,
                    env=env,
                )

        except Exception as exc:

            print("[waybar] fallo al relanzar:", exc)

    @classmethod
    def reset(cls):
        for p in (CONFIG_PATH, STYLE_PATH, COLORS_PATH):
            if os.path.exists(p):
                os.remove(p)